name: Build and Release

on:
  push:
    branches: ['master']
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
  pull_request:
    branches: [master]

jobs:
  Test-Build:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: '.cache/npm'
          cache-dependency-path: package-lock.json

      # Install
      - name: Install
        id: install-step
        run: npm ci --cache .cache/npm --prefer-offline

      # Build
      - name: Build
        id: build-step
        run: npm run build

  Deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setup NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Install
      - name: Install
        id: install-step
        run: npm ci --cache .cache/npm --prefer-offline

      # Build
      - name: Build
        id: build-step
        run: npm run build

      # Publish
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e #v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
